"use client";

import * as React from "react";
import { GitFork, Loader2 } from "lucide-react";
import type { Artifact } from "@/lib/types";

interface FlowStateProps {
  artifact: Artifact | null;
  generating?: boolean;
}

/* ──────────────────────────────────────────────────────────────────────────
   MermaidDiagram
   Renders a mermaid diagram string using the `mermaid` library (lazy loaded).
   The mermaid instance is cached at module level so initialization only runs once.
────────────────────────────────────────────────────────────────────────── */

// Module-level cache — mermaid is heavy; initialize exactly once.
let mermaidReady: Promise<typeof import("mermaid")["default"]> | null = null;

function getMermaid() {
  if (!mermaidReady) {
    mermaidReady = import("mermaid").then(({ default: mermaid }) => {
      mermaid.initialize({
        startOnLoad: false,
        theme: "dark",
        themeVariables: {
          background: "transparent",
          primaryColor: "#1a2a40",
          primaryTextColor: "#c9d6e3",
          primaryBorderColor: "#2a4060",
          lineColor: "#4a6a8a",
          secondaryColor: "#0d1a2a",
          tertiaryColor: "#0a1525",
          edgeLabelBackground: "#0d1420",
          clusterBkg: "#0a1420",
          titleColor: "#7ab8ff",
          nodeBorder: "#2a4a70",
          mainBkg: "#0f1e33",
          fontFamily: "inherit",
          fontSize: "13px",
        },
      });
      return mermaid;
    });
  }
  return mermaidReady;
}

function sanitizeMermaid(raw: string): string {
  return raw
    .split("\n")
    .map((line) =>
      line.replace(/(\w+)(\[[^\]]*\]|\([^)]*\)|\{[^}]*\})/g, (_m, id, label) => {
        const sanitized = label.replace(/[()]/g, "").replace(/\s+/g, " ").trim();
        return `${id}${sanitized}`;
      }),
    )
    .join("\n");
}

function MermaidDiagram({ chart }: { chart: string }) {
  const ref = React.useRef<HTMLDivElement>(null);
  const [svg, setSvg] = React.useState<string>("");
  const [error, setError] = React.useState<string>("");

  React.useEffect(() => {
    if (!chart.trim()) return;
    let cancelled = false;

    async function render() {
      try {
        const mermaid = await getMermaid();
        const id = `flow-${Math.random().toString(36).slice(2)}`;
        const { svg: rendered } = await mermaid.render(id, sanitizeMermaid(chart));
        if (!cancelled) setSvg(rendered);
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : "Render error");
      }
    }

    void render();
    return () => {
      cancelled = true;
    };
  }, [chart]);

  if (error) {
    return (
      <pre className="rounded-xl border border-red-500/15 bg-red-500/[0.05] px-4 py-3 text-xs leading-5 text-red-300/70">
        {error}
      </pre>
    );
  }

  if (!svg) {
    return (
      <div className="flex items-center gap-2 py-4 text-xs text-muted-foreground">
        <Loader2 className="size-3.5 animate-spin" />
        Rendering diagram…
      </div>
    );
  }

  return (
    <div
      ref={ref}
      className="mermaid-diagram overflow-x-auto"
      // SVG is generated by mermaid from our own artifact data — not user-supplied HTML
      // oxlint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}

/* ──────────────────────────────────────────────────────────────────────────
   FlowState
   Shows the architectural flow diagram embedded in the artifact.
   The agent emits a `flowDiagram` field (mermaid syntax) alongside code files.
────────────────────────────────────────────────────────────────────────── */
export function FlowState({ artifact, generating }: FlowStateProps) {
  if (generating && !artifact) {
    return (
      <div className="flex h-full items-center justify-center">
        <div className="flex flex-col items-center gap-3 text-muted-foreground">
          <Loader2 className="size-5 animate-spin" />
          <span className="text-sm">Analysing flow…</span>
        </div>
      </div>
    );
  }

  const chart = artifact?.flowDiagram;

  if (!chart) {
    return (
      <div className="flex h-full items-center justify-center px-6">
        <div className="flex max-w-[340px] flex-col items-center gap-4 text-center">
          <div className="flex size-12 items-center justify-center rounded-2xl border border-border bg-secondary/40">
            <GitFork className="size-5 text-muted-foreground" />
          </div>
          <div>
            <p className="text-sm font-medium text-foreground/80">No flow diagram yet</p>
            <p className="mt-1 text-xs leading-5 text-muted-foreground">
              In <span className="font-medium text-violet-400">Plan</span> or{" "}
              <span className="font-medium text-emerald-400">Agent</span> mode the agent draws
              an architectural flow diagram before writing any code.
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full overflow-auto p-5">
      <div className="mb-4 flex items-center gap-2">
        <GitFork className="size-4 text-muted-foreground" />
        <span className="text-sm font-medium text-foreground/70">Architectural flow</span>
      </div>
      <div className="rounded-2xl border border-border bg-card p-5">
        <MermaidDiagram chart={chart} />
      </div>
      {/* Raw source — collapsible */}
      <details className="mt-4 text-xs text-muted-foreground">
        <summary className="cursor-pointer select-none hover:text-foreground">
          View source
        </summary>
        <pre className="mono mt-2 overflow-auto rounded-xl border border-border bg-secondary/30 px-4 py-3 leading-5">
          {chart}
        </pre>
      </details>
    </div>
  );
}
