"use client";

import * as React from "react";
import { motion, AnimatePresence } from "motion/react";
import { GitFork, Send, Sparkles, X } from "lucide-react";

export interface ClarificationQuestion {
  id: string;
  question: string;
  hint?: string;
}

interface ClarificationPanelProps {
  open: boolean;
  questions: ClarificationQuestion[];
  originalPrompt: string;
  onSubmit: (answers: Record<string, string>) => void;
  onDismiss: () => void;
}

/**
 * ClarificationPanel
 *
 * Shown when the agent mode is "plan" and the planner needs more context before
 * drawing the architectural flow and building the step-by-step plan.
 *
 * The parent passes a list of questions generated by the planner. The user fills
 * them in and hits "Continue to plan" — the answers are forwarded back to the
 * submit handler so they can be appended to the original prompt.
 */
export function ClarificationPanel({
  open,
  questions,
  originalPrompt,
  onSubmit,
  onDismiss,
}: ClarificationPanelProps) {
  const [answers, setAnswers] = React.useState<Record<string, string>>({});

  // Reset answers whenever the panel opens with new questions
  React.useEffect(() => {
    if (open) setAnswers({});
  }, [open, questions]);

  const allAnswered = questions.every((q) => (answers[q.id] ?? "").trim().length > 0);

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!allAnswered) return;
    onSubmit(answers);
  }

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 8 }}
          transition={{ duration: 0.18, ease: "easeOut" }}
          className="fixed inset-0 z-40 flex items-end justify-center bg-black/60 p-4 sm:items-center"
        >
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 8 }}
            transition={{ duration: 0.2, ease: "easeOut", delay: 0.04 }}
            className="w-full max-w-lg overflow-hidden rounded-2xl border border-white/[0.09] bg-[#0d0d0d] shadow-2xl"
          >
            {/* Header */}
            <div className="flex items-start justify-between gap-3 border-b border-white/[0.07] px-5 py-4">
              <div className="flex items-center gap-2.5">
                <div className="flex size-8 items-center justify-center rounded-xl bg-violet-500/10">
                  <GitFork className="size-4 text-violet-400" />
                </div>
                <div>
                  <p className="text-sm font-medium text-white/85">Before I plan…</p>
                  <p className="text-xs text-white/38">A few quick questions to get this right</p>
                </div>
              </div>
              <button
                type="button"
                onClick={onDismiss}
                className="rounded-lg p-1.5 text-white/36 transition hover:bg-white/[0.07] hover:text-white"
              >
                <X className="size-4" />
              </button>
            </div>

            {/* Original prompt preview */}
            <div className="mx-5 mt-4 flex items-start gap-2 rounded-xl border border-white/[0.06] bg-white/[0.02] px-3.5 py-2.5">
              <Sparkles className="mt-0.5 size-3.5 shrink-0 text-violet-400/70" />
              <p className="text-xs leading-5 text-white/50 line-clamp-2">{originalPrompt}</p>
            </div>

            {/* Questions form */}
            <form onSubmit={handleSubmit} className="p-5">
              <div className="grid gap-4">
                {questions.map((q, i) => (
                  <label key={q.id} className="grid gap-2">
                    <div className="flex items-baseline gap-2">
                      <span className="text-[11px] font-medium text-violet-400/70">{i + 1}.</span>
                      <span className="text-sm text-white/75">{q.question}</span>
                    </div>
                    {q.hint && (
                      <p className="text-[11px] leading-4 text-white/30">{q.hint}</p>
                    )}
                    <textarea
                      rows={2}
                      value={answers[q.id] ?? ""}
                      onChange={(e) =>
                        setAnswers((prev) => ({ ...prev, [q.id]: e.target.value }))
                      }
                      placeholder="Your answer…"
                      className="w-full resize-none rounded-xl border border-white/[0.08] bg-white/[0.02] px-3.5 py-2.5 text-sm leading-5 text-white outline-none transition placeholder:text-white/22 focus:border-violet-500/40 focus:bg-white/[0.04]"
                    />
                  </label>
                ))}
              </div>

              <div className="mt-5 flex items-center justify-between gap-3">
                <button
                  type="button"
                  onClick={onDismiss}
                  className="text-xs text-white/36 transition hover:text-white/60"
                >
                  Skip — proceed without answers
                </button>
                <button
                  type="submit"
                  disabled={!allAnswered}
                  className="inline-flex h-9 items-center gap-2 rounded-xl bg-violet-600 px-4 text-sm font-medium text-white transition hover:bg-violet-500 disabled:cursor-not-allowed disabled:opacity-30"
                >
                  <Send className="size-3.5" />
                  Continue to plan
                </button>
              </div>
            </form>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

/**
 * generateClarificationQuestions
 *
 * Given a prompt, returns a list of targeted clarification questions.
 * This runs client-side as a heuristic — in production the planner LLM
 * would generate these. For now we generate sensible defaults based on
 * keywords found in the prompt.
 */
export function generateClarificationQuestions(prompt: string): ClarificationQuestion[] {
  const lower = prompt.toLowerCase();
  const questions: ClarificationQuestion[] = [];

  const hasAuth = /auth|login|sign.?in|user|account/.test(lower);
  const hasBilling = /billing|payment|stripe|subscription|credit|saas/.test(lower);
  const hasApi = /api|endpoint|route|backend|server/.test(lower);
  const hasDb = /database|postgres|libsql|sqlite|schema|table/.test(lower);

  questions.push({
    id: "target_users",
    question: "Who is the primary user of this app?",
    hint: "e.g. developers, end-consumers, internal team",
  });

  if (hasAuth) {
    questions.push({
      id: "auth_method",
      question: "What authentication method should be used?",
      hint: "e.g. email/password, OAuth (GitHub, Google), magic link",
    });
  }

  if (hasBilling) {
    questions.push({
      id: "billing_model",
      question: "Describe your billing / credit model.",
      hint: "e.g. pay-per-use credits, monthly subscription, free tier + upgrades",
    });
  }

  if (hasApi) {
    questions.push({
      id: "api_consumers",
      question: "Who consumes the API — a browser app, mobile, or third-party integrations?",
    });
  }

  if (hasDb) {
    questions.push({
      id: "data_sensitivity",
      question: "Are there data-sensitivity or compliance requirements?",
      hint: "e.g. GDPR, HIPAA, or no special requirements",
    });
  }

  if (questions.length < 2) {
    questions.push({
      id: "key_feature",
      question: "What is the single most important feature this app must nail?",
    });
  }

  return questions;
}
